### ISSUE TITLE
Swift 3 migration? 

### ISSUE THREAD

**Issue by regnerjr** [TheHolyGrail/Shrubbery#22]
Looks like there is a Swift 3 branch that has been created but does not point to the right place or have the migration done on it. The migration is pretty small and the Xcode 8.1 migrator does a pretty good job with this project. 

Is this something that I should open a PR against the Swift3 branch for? 

So far I did the simple thing which was run the migrator and then run the test to see if anything is broken, everything looks pretty good. You can see my branch over here: https://github.com/regnerjr/ELLog/tree/john/convert-to-swift3-xcode-8.1

There are various questions to be answered about api naming and open vs. public which will have to be considered before the Swift 3 version can be considered official, but this might be a good first step.

**Comment by angelodipaolo** [comment]
Opening a PR into the swift3 branch with your changes would be great. We can leave this issue open to discuss possible API naming updates to make for the official Swift 3 version.

**Comment by angelodipaolo** [comment]
A Swift 3 compatible release is now available as version [3.0.0](https://github.com/Electrode-iOS/ELLog/releases/tag/v3.0.0)
