### ISSUE TITLE
Long log messages cut off in iOS 10

### ISSUE THREAD

**Issue by nonsensery** [TheHolyGrail/Shrubbery#35]
#### Summary

It looks like there was a change to the way log messages are recorded in iOS 10, and now there is a length limit of 1024 bytes ([SO link](https://stackoverflow.com/questions/39584707/nslog-on-devices-in-ios-10-xcode-8-seems-to-truncate-why)).

#### Discussion

In general, this isn't a problem for us, but in developer builds, we allow logging of HTTP request and response bodies, which frequently exceed the limit. For now, our solution is to switch to `print()` for this logging.

**Comment by angelodipaolo** [comment]
Closing since this framework is deprecated.
