### ISSUE TITLE
Need to know more about crash Logs

### ISSUE THREAD

**Issue by hardikdevios** [TheHolyGrail/Shrubbery#4]
How it works actually ? did it caught Crash Automatically and save in file .. or do i have to write something else to save in file whenever the crash occurred. A bit more help would be very greatful ..

**Comment by bsneed** [comment]
It's not a crash reporting tool, it's a logging tool.  You _can_ hook it to your crash reporting tool if you'd like, which is what the Crashlytics destination is for.  The common usage section in the readme gives a decent explanation.  You use it like you'd use NSLog.  You can set a destination to go to a file if you like.  The files also have documentation inline, so check that out.
